name: Build AI Toolkit Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./aitoolkit
          file: ./aitoolkit/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/aitoolkit:${{ github.event.inputs.tag }}
          platforms: linux/amd64,linux/arm64
